### ISSUE TITLE
List of TPUs with States

### ISSUE THREAD

**Issue by corvitacvision** [google-coral/pycoral#63]
### Description

Hello all, is there any python wrapper of functions like list of tpus with showing states of them like "EDGE_TPU_STATE_NONE", "EDGE_TPU_STATE_UNASSIGNED" in PyCoral API?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.6

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @corvitacvision there is no python wrapper to know the states with PyCoral API.

 We used to have them in [edgetpu repo]( https://github.com/google-coral/edgetpu/blob/6d699665efdc5d84944b5233223c55fe5d3bd1a6/edgetpu/basic/edgetpu_utils.py ).  These are artificial states. They somewhat make sense only inside a single operating system process. E.g. if you run one python program the TPU state becomes "assigned", in another python program it's still "unassigned" because processes doesn't know about each other.

 We don't have any plans to add these states with PyCoral API. Thanks!
